### ISSUE TITLE
Request: Generate the web/build folder and add it to the template code as an example

### ISSUE THREAD

**Issue by architchandra** [miranj/craft-boilerplate#98]
Even if the built files have minimal code (eg. library JS and reset CSS). The asset manifest symlinks also don't work because the `web/build` folder does not exist.

Alternatively, build instructions like `npm ci && npm run dev` etc. can perhaps be added to the README inside the _Usage_ section. That should generate the build folder and fix the symlinks.

**Comment by rungta** [comment]
We had opted not to do this since that would be derived state, but I can see how it would be helpful to have a reference as a starting point as well.

> Alternatively, build instructions like npm ci && npm run dev etc. can perhaps be added to the README inside the Usage section.

These instructions are already present in the eventual project README, but I suppose we could add it to this starter project template’s README as well: https://github.com/miranj/craft-boilerplate/blob/4a06f01a9f99adf0843c2503ed8f8927c5e2f430/README.md.default#L40-L42
